LOAD DATA
INFILE 'CL1_ATTR_MAPPING_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CL1_ATTR_MAPPING_RANGE1  
  FIELDS TERMINATED BY ','
  (
		ATTRIBUTE_NAME,
		VERSION_NUMBER,
		DESCRIPTION,
		ATTRIBUTE_DYNAMIC_IND,
		ATTRIBUTE_DESTINATION,
		ATTRIBUTE_ACTIVITY,
		ATTRIBUTE_SHORT_NAME,
		ATTRIBUTE_TYPE
	)