LOAD DATA
INFILE 'CL1_AGENCY_RANGE1.ctl'
  TRUNCATE INTO TABLE BPT_CL1_AGENCY_RANGE1  
  FIELDS TERMINATED BY ','
  (
		AGENCY_CODE,
		AGENCY_NAME,
		AGENCY_GROUP_CODE,
		L3_GROUP_WEIGHT,
		L9_PROVINCE_CODE

	)