LOAD DATA
INFILE 'CUSTOMER_SUB_TYPES_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CUSTOMER_SUB_TYPES_RANGE1  
  FIELDS TERMINATED BY ','
  (
		CUSTOMER_TYPE,
		CUST_SUB_TYPE,
		DESCRIPTION,
		L9_BILL_DEF_DUE_DAYS
	)