LOAD DATA
INFILE 'UTL1_BD_HOLIDAYS_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_UTL1_BD_HOLIDAYS_RANGE1  
  FIELDS TERMINATED BY ','
  (
		CALENDAR_CODE,
		REOCCURRENCE_PERIOD,
		REOCCURRENCE_DAY,
		REOCCURRENCE_MONTH,
		OCCURRENCE_YEAR,
		DURATION,
		DAY_TYPE,
		BD_HOLIDAY_ID
	)