LOAD DATA
INFILE 'AR1_GENERIC_CODES_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_AR1_GENERIC_CODES_RANGE1  
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  (
		ID,
		TYPE,
		CODE,
		LANGUAGE,
		DESCRIPTION,
		BE
	)