LOAD DATA
INFILE 'AR1_CHARGE_CODE_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_AR1_CHARGE_CODE_RANGE1  
  FIELDS TERMINATED BY ','
  (
		CHARGE_CODE,
		REVENUE_TYPE,
		GROUP_TYPE,
		BALANCE_IMPACT_CODE,
		MANUAL_OC_CREATE_IND,
		DESCRIPTION
	)