LOAD DATA
INFILE 'Backout_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_Backout_RANGE1  
  FIELDS TERMINATED BY ','
  (
		BACKOUT_REASON_CODE,
		BACKOUT_REASON_TYPE,
		DCK_CHARGE_INDICATOR,
		BACKOUT_REASON_CODE_DESC,
		OVERWRITE_DCK,
		CHARGE_AMOUNT,
		DCK_CHARGE_CODE
	)