LOAD DATA
INFILE 'CCS1_RESOURCE_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CCS1_RESOURCE_RANGE1  
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  (
		BE,
		RESOURCE_ID,
		VERSION,
		SYS_CREATION_DATE,
		SYS_UPDATE_DATE,
		OPERATOR_ID,
		APPLICATION_ID,
		DL_SERVICE_CODE,
		DL_UPDATE_STAMP,
		EFFECTIVE_DATE,
		RESOURCE_NAME,
		SHORT_DESC,
		DESCRIPTION,
		RESOURCE_TYPE_CODE,
		LOCATION_TYPE_CODE,
		FILENAME,
		FILE_PATH,
		CONTENT
	)