LOAD DATA
INFILE 'CCS1_REQ_TYPE_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CCS1_REQ_TYPE_RANGE1  
  FIELDS TERMINATED BY ','
  (
		REQUEST_TYPE_ID,
		SYS_CREATION_DATE,
		SYS_UPDATE_DATE,
		OPERATOR_ID,
		DL_SERVICE_CODE,
		DL_UPDATE_STAMP,
		CODE,
		APP_ID,
		ENTITY_TYPE_ID,
		ACTIVITY_ID,
		ACTIVITY_RESULT_ID,
		COMMUNICATION_TYPE_ID,
		TEMPLATE_ID,
		BATCH_INPUT_IND,
		BATCH_OUTPUT_IND,
		SHORT_DESC,
		DESCRIPTION
	)