LOAD DATA
INFILE 'CCS1_REQ_TYPE_RESOURCE_RANGE1.dat' 
  TRUNCATE INTO TABLE BPT_CCS1_REQ_TYPE_RES_RANGE1  
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  (
		REQUEST_TYPE_ID,
		RESOURCE_ID_LIST,
		RESOURCE_ID
	)