LOAD DATA
INFILE 'CCS1_COMMUNICATION_TYPE_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CCS1_COMM_TYPE_RANGE1  
  FIELDS TERMINATED BY ','
  (
		COMMUNICATION_TYPE_ID,
		SYS_CREATION_DATE,
		SYS_UPDATE_DATE,
		OPERATOR_ID,
		DL_SERVICE_CODE,
		DL_UPDATE_STAMP,
		CODE,
		SHORT_DESC,
		DESCRIPTION
	)