LOAD DATA
INFILE 'CCS1_TEMPLATE_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CCS1_TEMPLATE_RANGE1  
  FIELDS TERMINATED BY ','
  (
		BE,
		TEMPLATE_ID,
		SYS_CREATION_DATE,
		SYS_UPDATE_DATE,
		OPERATOR_ID,
		DL_SERVICE_CODE,
		DL_UPDATE_STAMP,
		CODE,
		APP_ID,
		EXTERNAL_REFERENCE,
		SHORT_DESC,
		DESCRIPTION
	)