LOAD DATA
INFILE 'CL1_AR_DEBT_TYPE_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CL1_AR_DEBT_TYPE_RANGE1  
  FIELDS TERMINATED BY ','
  (
		DEBT_TYPE,
		DESCRIPTION,		
		DEBT_AMOUNT_STATE,
		GROUP_CLASS_TYPE
	)