LOAD DATA
INFILE 'CL1_BPM_PROCESS_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CL1_BPM_PROCESS_RANGE1  
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  (
		PROCESS_NAME,
		PROCESS_TYPE,
		DESCRIPTION,
		APPLICATION_ID
	)