LOAD DATA
INFILE 'CL1_AR_FINANCE_ACTIVITY_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CL1_AR_FIN_ACTIVITY_RANGE1  
  FIELDS TERMINATED BY ','
  (
		FINANCIAL_ACTIVITY_CODE,
		COLLECTION_STATE,
		ACC_CR_AMT_STATE,
		DESCRIPTION
	)