LOAD DATA
INFILE 'CL1_GENERIC_CODES_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CL1_GENERIC_CODES_RANGE1  
  FIELDS TERMINATED BY ','
  (
		BE_ID,
		TYPE,
		CODE,
		LANGUAGE,
		APPLICATION_ID,
		SHORT_DESC,
		DESCRIPTION
	)