LOAD DATA
INFILE 'CL1_PROPERTIES_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CL1_PROPERTIES_RANGE1  
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  (
		PTYPE,
		PNAME,
		SYS_CREATION_DATE,
		SYS_UPDATE_DATE,
		OPERATOR_ID,
		APPLICATION_ID,
		DL_SERVICE_CODE,
		DL_UPDATE_STAMP,
		PVALUE,
		SHORT_DESC,
		DESCRIPTION,
		PCONSTRAINTS
	)