LOAD DATA
INFILE 'CL1_PA_POLICY_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CL1_PA_POLICY_RANGE1  
  FIELDS TERMINATED BY ','
  (
		VERSION_NUM,
		PRIORITY,
		RECOMMENDATION_CRITERIA,
		PROCESS_NAME,
		MIN_PAST_DUE_AMOUNT_PERCENT,
		MIN_INSTALL_DUE_AMT_PERCENT,
		MIN_PAST_DUE_AMOUNT,
		MIN_INSTALLMENT_DUE_AMOUNT,
		MAX_INSTALLMENT_COUNT,
		MAX_INSTALLMENT_INTERVAL,
		GRACE_PERIOD,
		DEFAULT_INSTALMMENT_COUNT,
		INTERVAL_TYPE,
		INTERVAL_FACTOR,
		SHORT_DESC,
		DESCRIPTION
	)