LOAD DATA
INFILE 'CUSTOMER_TYPE_RANGE1.dat'
  TRUNCATE INTO TABLE BPT_CUSTOMER_TYPE_RANGE1  
  FIELDS TERMINATED BY ','
  (
		CUSTOMER_TYPE,
		CUSTTP_DESC,
		NAME_TYPE,
		DEF_ADDR_TYPE,
		ANONYMOUS_IND,
		CRDT_EVAL_REQ_IND,
		INIT_CRDT_CLASS,
		PAYMENT_CATEGORY,
		DEF_PYM_MTD,
		DEF_PYM_TP,
		ACCT_BAL_POLICY,
		CYC_POPULATION_CD,
		BILL_DEF_DOC_TYPE,
		BILL_PRODUCT_IND,
		BILL_ZERO_BAL_IND,
		BILL_ITEM_TAX_IND,
		BILL_DEF_DUE_DAYS,
		DFLT_SUB_TYPE,
		ENTITY_LOCK_TYPE,
		FINANCIAL_LOCK_TYPE
	)