LOAD DATA
INFILE 'Payment_RANGE3.dat'
  TRUNCATE INTO TABLE BPT_Payment_RANGE3  
  FIELDS TERMINATED BY ','
  (
		SOURCE_ID,
		SOURCE_TYPE,
		EXCEPTION_CONTROL_ACCOUNT,
		Currency,
		DEPOSIT_BANK_CODE,
		DEPOSIT_BANK_ACCOUNT_NUMBER
	)